### ISSUE TITLE
As a user, I can visit your site and it looks awesome

### ISSUE THREAD

**Issue by francescoannetta** [mightyLake/mgt656-spring-2015-project#17]

**Comment by smilingPartridge** [comment]
I think that for Sprint 3, we need to split this up into many stories so we can delegate & work in chunks. 

Ex: 
- one story for header, 
- another story for footer, 
- another story for CSS on the home page, 
- a fourth for CSS on the events page, 
- and so on.

**Comment by smilingPartridge** [comment]
one of these tasks needs to be the layout page
