### ISSUE TITLE
As a user, I can visit your new events page and be presented with reasonable options

### ISSUE THREAD

**Issue by francescoannetta** [mightyLake/mgt656-spring-2015-project#28]

**Comment by francescoannetta** [comment]
<form id="create-event" method="POST">

The form and its inputs should be given the correct class(es) to use bootstrap form styling. This is secondary, but it would put us in a better spot for next week.

See: http://getbootstrap.com/css/#forms

Bootstrap is already included.

**Comment by francescoannetta** [comment]
What if the month doesn't have 31 days?

**Comment by francescoannetta** [comment]
....
-      <option value="20" >20</option>
-      <option value="21" >21</option>
-      <option value="22" >22</option>
-      <option value="23" >23</option>

These labels are not very user friendly. Using AM, PM suffixes would probably be best.

**Comment by dhatch** [comment]
There should not be a `0` option for day.  I missed this in the code review.

@francescoannetta Could you create a new PR with this fix?

**Comment by francescoannetta** [comment]
This was covered by PR #37
