### ISSUE TITLE
As a user I can visit your page for creating new events at /events/new

### ISSUE THREAD

**Issue by smilingPartridge** [mightyLake/mgt656-spring-2015-project#4]
- [x] It should have a `form` for creating events. The `form` should have attribute `method="POST"`.
- [x] I must specify the following attributes of an event: title, location, image, year, month, day, hour, and minute.
- [x] There must be a `form` element with `name={{field}}` for each of these, where `{{field}}` is title, location, etc.
- [x] Every form element requires a label element with appropriate for attribute. For example:
  
  ``` html
   <form method="POST">
  <label for="title">Put title here:</label>
   <input type="text" name="title" id="title">
   ... 
   </form>
  ```
- [x] The year, month, day, hour, and minute form elements should be select elements.
- [x] The minute should only have 0, and 30 as selections. (At the hour and half hour).
- [x] The hour select should be in 24-hour time format: 0-23 are selectable.
- [x] The month select should have integer value attributes and refer to months by their names: January, February, etc.
- [x] You should only be able to schedule events in 2015 and 2016
- [x] I can click a input element to submit the event. This element should have `id="submit"` and `type="submit"`.
  - [x] If the submitted form is valid, I am redirected to the detail page for that new event. This redirect is accomplished using a "302" HTTP response. (See the documentation for the Express.js response redirect method)

**Comment by dhatch** [comment]
Pretty large chunk of work, probably should be broken into additional stories.

**Comment by dhatch** [comment]
Notify #15 when finished.
