### ISSUE TITLE
As an attendee, I can visit the event detail page to RSVP for an event.

### ISSUE THREAD

**Issue by dhatch** [mightyLake/mgt656-spring-2015-project#7]

**Comment by francescoannetta** [comment]
- [x] I submit my email address by filling in a form. The form has method="POST" and contains an input element with attributes type, id, and name all set to "email".
  -  [ ] If I submit an email address that does not end in "@yale.edu", the form is redisplayed with an error message. (You should accept any valid "@yale.edu" ending: "@Yale.edu", "@yALe.edu", etc.).
  -  [ ] The error messages displayed should be in a ul with class="form-errors" in the same fashion as described in the event creation errors described.
- [x] If I submit a valid email address, I see the event detail page again and it shows my email address on there along with the other attendees.

**Comment by smilingPartridge** [comment]
- An astute member of our class pointed out to me that the tests for the event detail pages do not have corresponding prose on the project description -- https://mgt656.som.yale.edu/project -- which makes it less easy to understand what needs to be done. It should be: as a user, I can visit a "detail page" for each event at a URL like `/events/0`, `/events/1`, etc. Each of those pages contain the event details: an h1 tag with id="title" containing the title; a span tag with id="date" containing the date; a span tag with id="location" containing the location; an img tag with id="image" containing the event image; and a ul tag with id="attendees" containing a list of the attendees.

**Comment by francescoannetta** [comment]
notify #26 & #29 @francescoannetta when complete

**Comment by dhatch** [comment]
@smilingPartridge Could you push your latest?  This is blocking #26 and #29 (analytics).  We need to start those today if possible.

**Comment by smilingPartridge** [comment]
@dhatch -- all should have been pushed on Friday at 5:00 p.m. When I checked, it looked like the previous push had updated with my most recent changes. Is that how it looks to you? (If correct, event detail page and all associated RSVP tests should now pass.)
